[package]
name = "hello_macro_test"
version = "0.1.0"
edition = "2018"

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derve = { path = "../hello_macro_derve" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
